---
- name: Ensure '{{ pg_home_dir }}/.ssh' exists for postgres
  file:
    path: '{{ pg_home_dir }}/.ssh'
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Generate an RSA keypair for pgpool if not exists
  openssh_keypair:
    path: '{{ pg_home_dir }}/.ssh/{{ ssh_key_file }}'
    type: rsa
    size: 2048
    owner: postgres
    group: postgres
    mode: '0600'
    force: false
    comment: "pgpool {{ inventory_hostname }}"

- name: Slurp local public key
  slurp:
    path: "{{ pg_home_dir }}/.ssh/{{ ssh_key_file }}.pub"
  register: local_pubkey

- name: Ensure authorized_keys of user postgres exists
  file:
    path: "{{ pg_home_dir }}/.ssh/authorized_keys"
    state: touch
    owner: postgres
    group: postgres
    mode: '0600'

- name: Collect pgpool public keys from all cluster hosts
  slurp:
    path: "{{ pg_home_dir }}/.ssh/{{ ssh_key_file }}.pub"
  delegate_to: "{{ item }}"
  loop: "{{ groups['all'] }}"
  register: slurped_cluster_keys
  failed_when: false
  changed_when: false

- name: Add cluster public keys to local authorized_keys
  authorized_key:
    user: postgres
    key: "{{ item.content | b64decode }}"
    state: present
  loop: "{{ slurped_cluster_keys.results }}"
  when:
    - item.content is defined
    - (item.content | length) > 0
  loop_control:
    label: "{{ item.item }}"

- name: Distribute local public key to all available cluster hosts
  authorized_key:
    user: postgres
    key: "{{ local_pubkey.content | b64decode }}"
    state: present
  delegate_to: "{{ item }}"
  loop: "{{ groups['all'] }}"
  failed_when: false
  loop_control:
    label: "{{ item }}"
