all:
  children:
    clickhouse:
      hosts:
        node-db-01:
          ansible_host: 192.168.56.111
          node_ip: 192.168.56.111
          clickhouse_node_id: 1
          clickhouse_shard_id: 1
          clickhouse_replica_name: node-db-01
          ansible_ssh_private_key_file: "{{ playbook_dir }}/../../vagrant/postgresql/.vagrant/machines/db_1/virtualbox/private_key"
        node-db-02:
          ansible_host: 192.168.56.112
          node_ip: 192.168.56.112
          clickhouse_node_id: 2
          clickhouse_shard_id: 2
          clickhouse_replica_name: node-db-02
          ansible_ssh_private_key_file: "{{ playbook_dir }}/../../vagrant/postgresql/.vagrant/machines/db_2/virtualbox/private_key"
        node-db-03:
          ansible_host: 192.168.56.113
          node_ip: 192.168.56.113
          clickhouse_node_id: 3
          clickhouse_shard_id: 3
          clickhouse_replica_name: node-db-03
          ansible_ssh_private_key_file: "{{ playbook_dir }}/../../vagrant/postgresql/.vagrant/machines/db_3/virtualbox/private_key"
  vars:
    # tell every SSH connection in this play to skip host‑key checking
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes'
    ansible_user: vagrant
