#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/postgresql-ha-pgpool

- name: Restart rsyslog
  become: true
  systemd:
    name: rsyslog
    state: restarted

- name: Restart PostgreSQL
  become: true
  systemd:
    name: postgresql@{{ postgresql_version }}-main.service
    state: restarted
  listen: Restart PostgreSQL

- name: Restart PgPool
  become: true
  systemd:
    name: pgpool2.service
    state: restarted
  listen: Restart PgPool

- name: Restart keepalived
  become: true
  systemd:
    name: keepalived
    state: restarted

- name: Reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: Restart PgBouncer
  become: true
  systemd:
    name: pgbouncer
    state: restarted

- name: Reload PgBouncer
  become: true
  systemd:
    name: pgbouncer
    state: reloaded
