image:
  registry: docker.io
  repository: bitnamilegacy/minio
  tag: 2025.7.23-debian-12-r3

clientImage:
  registry: docker.io
  repository: bitnamilegacy/minio-client
  tag: 2025.7.21-debian-12-r2

auth:
  existingSecret: minio-secret

console:
  enabled: false

service:
  type: ClusterIP
  ports:
    api: 9000
    console: 9001

mode: distributed

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - minio
        topologyKey: kubernetes.io/hostname