#SPDX-License-Identifier: MIT-0
---
# defaults file for clickhouse

clickhouse_deploy_dir: '/u01/clickhouse'
clickhouse_image: 'clickhouse/clickhouse-server:26.4'
clickhouse_cluster_name: 'dwh_cluster_3node'
clickhouse_db: 'analytics'
clickhouse_user: 'dwh_user'

clickhouse_http_port: 8123
clickhouse_tcp_port: 9000
clickhouse_interserver_port: 9009
clickhouse_keeper_port: 9181
clickhouse_keeper_raft_port: 9234

# HAProxy settings
haproxy_image: 'haproxy:2.8-alpine'
haproxy_http_port: 8124
haproxy_tcp_port: 9001
haproxy_stats_port: 8404

# Keepalived settings
keepalived_vip: '192.168.56.110'
keepalived_interface: 'enp0s8'
keepalived_router_id: 56
keepalived_auth_pass: 'ChKeeP@110'
