apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-tools
  namespace: backend
  labels:
    app: network-tools 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-tools
  template:
    metadata:
      labels:
        app: network-tools
    spec:
      containers:
        - name: network-tools
          image: duyle95/network-tools
          imagePullPolicy: Always
          command: ["/bin/sh"]
          stdin: true
          tty: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      nodeSelector:
        dedicated: "app"
        # kubernetes.io/hostname: "replace-node-name-to-deploy-into-that-node"
      tolerations:
        - key: "dedicated"
          value: "app"
          operator: "Equal"
          effect: "NoSchedule"