{{- $secretName := .Values.secret.name -}}
{{- $secretKey := "api-key" -}}
{{- $apiKeyLength := int .Values.secret.apiKeyLength -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $apikey := randAlphaNum $apiKeyLength -}}
{{- if and $existingSecret (index $existingSecret.data $secretKey) -}}
  {{- $apikey = index $existingSecret.data $secretKey | b64dec -}}
{{- end -}}
{{- $allowedNamespaces := join "," .Values.reflector.allowedNamespaces -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ $allowedNamespaces | quote }}
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: {{ $allowedNamespaces | quote }}
type: Opaque
data:
  AUTHENTICATION_APIKEY_ALLOWED_KEYS: {{ $apikey | b64enc | quote }}