# Global settings
global:
  images:
    envoyGateway:
      image: "docker.io/envoyproxy/gateway:v1.5.0"
      pullPolicy: IfNotPresent
    ratelimit:
      image: "docker.io/envoyproxy/ratelimit:3e085e5b"
      pullPolicy: IfNotPresent

config:
  # -- EnvoyGateway configuration. Visit https://gateway.envoyproxy.io/docs/api/extension_types/#envoygateway to view all options.
  envoyGateway:
    provider:
      kubernetes:
        watchMode:
          type: Namespaces
          namespaces: ["default", "api-gateway", "backend", "redis"] # list namespace mà Envoy Gateway sẽ theo dõi để tìm các Kubernetes resources liên quan đến Gateway API (HTTPRoute, GRPCRoute, TLSRoute, v.v.).
    extensionApis:
      enableEnvoyPatchPolicy: true

deployment: # envoy gateway
  replica: 1
  pod:
    labels:
      host-network: "true"
    tolerations: &a1
      - key: dedicated
        operator: Equal
        value: "gateway"
        effect: NoSchedule
    nodeSelector: &a2
      dedicated: "gateway"

certgen: 
  # job certgen tạo:
  # CA cert tự ký
  # Server cert cho Envoy Gateway controller
  # Client cert cho envoy proxy
  # Những cert này được lưu vào Secret trong namespace envoy-gateway-system, dùng giao tiếp nội bộ của envoy gateway
  job:
    tolerations: *a1
    nodeSelector: *a2
