global_defs {
    router_id clickhouse_node1
    enable_script_security
    script_user root
}

vrrp_script check_haproxy {
    script "/etc/keepalived/check_haproxy.sh"
    interval 2
    weight -20
    fall 2
    rise 2
}

vrrp_instance VI_CLICKHOUSE {
    state MASTER
    interface enp0s8
    virtual_router_id 56
    priority 101
    advert_int 1

    unicast_src_ip 192.168.56.111
    unicast_peer {
        192.168.56.112
        192.168.56.113
    }

    authentication {
        auth_type PASS
        auth_pass ChKeeP@110
    }

    virtual_ipaddress {
        192.168.56.110/24 dev enp0s8
    }

    track_script {
        check_haproxy
    }
}
