{{- $secretName := .Values.secret.name -}}
{{- $secretKey := "root-password" -}}
{{- $passwordLength := int .Values.secret.passwordLength -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $password := randAlphaNum $passwordLength -}}
{{- if and $existingSecret (index $existingSecret.data $secretKey) -}}
  {{- $password = index $existingSecret.data $secretKey | b64dec -}}
{{- end -}}
{{- $allowedNamespaces := join "," .Values.reflector.allowedNamespaces -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ $allowedNamespaces | quote }}
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: {{ $allowedNamespaces | quote }}
type: Opaque
data:
  root-user: {{ "admin" | b64enc | quote }}
  root-password: {{ $password | b64enc | quote }}