master:
  hosts:
    master-01:
      ansible_host: 192.168.56.101
      node_name: master-01
      rke2_tls_san: ["node-master-01", "192.168.56.101"]
    master-02:
      ansible_host: 192.168.56.102
      node_name: master-02
      rke2_tls_san: ["node-master-02", "192.168.56.102"]
    master-03:
      ansible_host: 192.168.56.103
      node_name: master-03
      rke2_tls_san: ["node-master-03", "192.168.56.103"]

worker:
  hosts:
    worker-01:
      ansible_host: 192.168.56.104
      node_name: worker-01
      labels: dedicated=backend
      taints: dedicated=backend:NoSchedule
    worker-02:
      ansible_host: 192.168.56.105
      node_name: worker-02
      labels: dedicated=backend
      taints: dedicated=backend:NoSchedule
    worker-03:
      ansible_host: 192.168.56.106
      node_name: worker-03
      labels: dedicated=backend
      taints: dedicated=backend:NoSchedule

gateway:
  hosts:
    gateway-01:
      ansible_host: 192.168.56.107
      node_name: gateway-01
      labels: dedicated=gateway
      taints: dedicated=gateway:NoSchedule

db:
  hosts:
    db-01:
      ansible_host: 192.168.56.108
      node_name: db-01
      labels: dedicated=db
      taints: dedicated=db:NoSchedule
    db-02:
      ansible_host: 192.168.56.109
      node_name: db-02
      labels: dedicated=db
      taints: dedicated=db:NoSchedule
    db-03:
      ansible_host: 192.168.56.110
      node_name: db-03
      labels: dedicated=db
      taints: dedicated=db:NoSchedule


rke2:
  children:
    master: {} 
    worker: {}
    gateway: {}
    db: {}

  vars:
    # tell every SSH connection in this play to skip host‑key checking
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_user: vagrant
