api:
  replicaCount: 2

frontend:
  replicaCount: 2

sandbox:
  replicaCount: 2

worker:
  replicaCount: 2

proxy:
  enabled: true
  proxy: http://test-proxy:3128
  ca_cert:
    enabled: true
    content: |-
      -----BEGIN CERTIFICATE-----
      PUT PROXY CONTENT HERE
      -----END CERTIFICATE-----