apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: backend
data:
  POSTGRES_USER: "postgres"
  # POSTGRES_HOST: "192.168.56.110"
  POSTGRES_HOST: "192.168.56.141"
  POSTGRES_PORT: "5432"
