apiVersion: ENC[AES256_GCM,data:4po=,iv:9K8cBOkTC80fkh0QAtlMi3kqfqkor+9jyAplF8Q0OXI=,tag:HXQMKJjccL84b4AYW/PI1g==,type:str]
kind: ENC[AES256_GCM,data:+KLikb7s,iv:+rWTlaPiPXP+MKKjZ3qKBv65pB4HLUJC8IWx0wA/wGc=,tag:gBXTeg0w/bN5BfqU6jLu+A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iwqjxUst2+BvwGr13a1Sw3U=,iv:Cq9o13mLVo4XV7NCtmGPUreAkrsSNCb1JGYoSF2iWxE=,tag:EXBXPP/qrYfp+D9rAVDvnw==,type:str]
    namespace: ENC[AES256_GCM,data:k8WMqFJfLg==,iv:w5A2P47lH9RMsfzvOjRIVE3+gjjyGuMGkd77Md6eTFc=,tag:JD90ZzucRD/ODY0KNGNbxQ==,type:str]
type: ENC[AES256_GCM,data:a+X/bJNO,iv:hIGqg3tlpYI8PwDfztDZiLAQy5Wc5/OVBYE2Gh54E98=,tag:9TXEzFu4Cxlur22o3xNUig==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:NIMGD0ynQ/XTzE8R4Mw=,iv:nDRLCM9by7enIqhqIazC1pYJQfVaqxPke2fvL965RJc=,tag:/ZYo6EuFFfjp8iy5xTgFqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1twejs0zx2qkc9hcprkphjn7exnrz3czhg0enlr5unlyc0f2syv9qw0dssg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT3JxQWQ3bjh4dENibzBw
            RVVPWnd0TmJKaU9QaWR4RnZwaWFoV2Z4dHlZCjUvQStzb0NTdHNrQ0hRVHVrbFVU
            L3ZmWjR5czBCdmtkai93anltNC9mYm8KLS0tIE9BNUdVbGFDQmRGUnVZSHczVGVl
            R1RybTRtaXVsb2JmK3YyZ1ZIb0QwQW8K8em1duCTiZsl60JaRr0e6uaRW0YPlboy
            GoP1flHpXd/p+lu0bj3WViA1OMvnFpbyiHcMXuufRAq6+3OUoQ0GCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T16:02:21Z"
    mac: ENC[AES256_GCM,data:6Hn/6mnus9BRM6Tv/EcXD1IBgkalURUhRCuIvh2KWmQ2ZsPMPty20G3a7fTSw0wYP36C9TWm2bbc2sSn4ulcaUm3b3s6IGrB7JB43fNyVPLbxjvwWXsYGcxq+I86C77KP57U3WAZj5y3BY+m+K9KuwEWQeEFObAfedZ1o8N/i2A=,iv:yNebnukK9a1wpXvjFlHEO8P8i7+p8AccLDr7nH2KQz0=,tag:mEZJibMbUcnPlaVPSP5jPQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
