---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dify.fullname" . }}-api
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    {{- include "dify.global.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dify.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dify.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
        {{- include "dify.global.labels" . | nindent 8 }}
        app: dify-api
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dify.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}-api
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ coalesce .Values.api.image.tag .Values.global.image.tag .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
            - name: MODE
              value: "api"
            {{- include "dify.commonEnvs" . | nindent 12 }}
            {{- include "dify.commonBackendEnvs" . | nindent 12 }}
            {{- with .Values.global.extraBackendEnvs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.api.envs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: CODE_EXECUTION_ENDPOINT
              value: "http://{{ include "dify.fullname" . }}-sandbox.{{ .Release.Namespace }}.svc.cluster.local"
            - name: CODE_EXECUTION_API_KEY
            {{- if .Values.sandbox.apiKeySecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sandbox.apiKeySecret }}
                  key: sandbox-api-key
            {{- else if .Values.sandbox.apiKey }}
              value: {{ .Values.sandbox.apiKey | quote }}
            {{- else }}
            {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
          {{- with .Values.api.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}

      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
