{{- if .Values.pluginDaemon.enabled }}
# pluginDaemon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dify.fullname" . }}-plugin-daemon
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: plugin-daemon
    {{- include "dify.global.labels" . | nindent 4 }}
spec:
  {{- if hasKey .Values.pluginDaemon "autoscaling" }}
  {{- if and (hasKey .Values.pluginDaemon "autoscaling") (not .Values.pluginDaemon.autoscaling.enabled) }}
  replicas: {{ .Values.pluginDaemon.replicaCount | default 1 }}
  {{- end }}
  {{- else }}
  replicas: 1
  {{- end }}
  strategy: {{- toYaml .Values.pluginDaemon.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "dify.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: plugin-daemon
  template:
    metadata:
      {{- with .Values.pluginDaemon.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dify.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: plugin-daemon
        {{- include "dify.global.labels" . | nindent 8 }}
        app: dify-plugin-daemon
    spec:
      {{- with .Values.pluginDaemon.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dify.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.pluginDaemon.podSecurityContext | nindent 8 }}


      {{- if (and .Values.proxy.enabled .Values.proxy.ca_crt.enabled) }}
      # initContainers use to set CA cert of proxy
      initContainers:
        - name: install-ca-certificate
          image: {{ .Values.proxy.ca_crt.image }}
          command:
            - sh
            - -c
            - |
              set -e
              sed -i 's/https/http/' /etc/apk/repositories && \
              apk update && \
              apk add --no-cache ca-certificates && \
              cp /ca-config/proxy_ca.crt /usr/local/share/ca-certificates/proxy_ca.crt && \
              update-ca-certificates && \
              cp -a /etc/ssl/certs/ca-certificates.crt /cert-store/ca-certificates.crt || true
          volumeMounts:
            - name: dify-proxy-volume
              mountPath: /ca-config
            - name: ca-certs-store
              mountPath: /cert-store
          env:
            {{- include "dify.commonBackendEnvs" . | nindent 12 }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}-plugin-daemon
          securityContext:
            {{- toYaml .Values.pluginDaemon.securityContext | nindent 12 }}
          image: "{{ .Values.pluginDaemon.image.repository }}:{{ .Values.pluginDaemon.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.pluginDaemon.image.pullPolicy }}
          env:
            - name: DIFY_INNER_API_URL
              value: "http://{{ include "dify.fullname" . }}-api-svc:{{ .Values.api.service.port }}"
            - name: SERVER_KEY
            {{- if .Values.pluginDaemon.serverKeySecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pluginDaemon.serverKeySecret }}
                  key: plugin-daemon-key
            {{- else if .Values.pluginDaemon.serverKey }}
              value: {{ .Values.pluginDaemon.serverKey | quote }}
            {{- else }}
            {{- end }}
            - name: DIFY_INNER_API_KEY
            {{- if .Values.pluginDaemon.difyInnerApiKeySecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pluginDaemon.difyInnerApiKeySecret }}
                  key: plugin-dify-inner-api-key
            {{- else if .Values.pluginDaemon.difyInnerApiKey }}
              value: {{ .Values.pluginDaemon.difyInnerApiKey | quote }}
            {{- else }}
            {{- end }}
            - name: PLUGIN_WORKING_PATH
              value: /app/storage/cwd
            {{- include "dify.commonEnvs" . | nindent 12 }}
            {{- include "dify.commonBackendEnvs" . | nindent 12 }}
            {{- with .Values.global.extraEnvs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.global.extraBackendEnvs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.pluginDaemon.envs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

          # Volume Mounts
          {{- if (and .Values.proxy.enabled .Values.proxy.ca_crt.enabled) }}
          volumeMounts:
            - name: ca-certs-store
              mountPath: "/etc/ssl/certs"
          {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.pluginDaemon.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.pluginDaemon.resources | nindent 12 }}

      # Volumes
      {{- if (and .Values.proxy.enabled .Values.proxy.ca_crt.enabled) }}
      volumes:
        - name: dify-proxy-volume
          secret:
            secretName: dify-proxy-volume
        - name: ca-certs-store
          emptyDir: {}
      {{- end }}

      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pluginDaemon.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
