- name: Copy local-path-storage.yaml to remote server
  copy:
    src: 'local-path-storage-v0.0.32.yaml'
    dest: '/tmp/local-path-storage.yaml'
    mode: '0644'
    owner: root
    group: root

- name: Deploy storageclass local-path-provisioner
  shell: |
    kubectl apply -f /tmp/local-path-storage.yaml 
  register: result

- name: Show result of deploy storageclass local-path-provisioner
  debug: 
    var: result

- name: Set it as default storageclass
  shell: |
    kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  register: result

- name: Show result 
  debug:
    var: result
